<center>
<img src="../../img/ods_stickers.jpg" />
    
## [mlcourse.ai](mlcourse.ai) â€“ Open Machine Learning Course 
Author: Arina Lopukhova (@erynn). Edited by [Yury Kashnitskiy](https://yorko.github.io) (@yorko). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.

<h1><center>Assignment #1. Fall 2018</center></h1>
<h2><center>Exploratory data analysis of Olympic games with Pandas</center></h2>

__There are ten questions about [120 years of Olympic history: athletes and results](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results/version/2) dataset in this task. Your task is to fill in the missing Python code and choose answers in [this web-form](https://docs.google.com/forms/d/179HYvlF_0x435CWdu2aOtR9a3flh0YCQXXNXhXaKw2M).__

Download the file `athlete_events.csv` from [Kaggle page](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results). The dataset has the following features (copied from Kaggle):

- __ID__ - Unique number for each athlete
- __Name__ - Athlete's name
- __Sex__ - M or F
- __Age__ - Integer
- __Height__ - In centimeters
- __Weight__ - In kilograms
- __Team__ - Team name
- __NOC__ - National Olympic Committee 3-letter code
- __Games__ - Year and season
- __Year__ - Integer
- __Season__ - Summer or Winter
- __City__ - Host city
- __Sport__ - Sport
- __Event__ - Event
- __Medal__ - Gold, Silver, Bronze, or NA

In [1]:
import pandas as pd

In [2]:
# Change the path to the dataset file if needed. 
PATH = '../../data/athlete_events.csv'

In [3]:
data = pd.read_csv(PATH)
data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

__1. How old were the youngest male and female participants of the 1996 Olympics?__

- 16 and 15
- 14 and 12 
- 16 and 12
- 13 and 11

In [13]:
data[(data['Sex'] == 'M') & (data['Year'] == 1996)]['Age'].min(), \
data[(data['Sex'] == 'F') & (data['Year'] == 1996)]['Age'].min() #14 12

(14.0, 12.0)

__2. What was the percentage of male gymnasts among all the male participants of the 2000 Olympics? Round the answer to the first decimal.__

*Hint:* here and further if needed drop duplicated sportsmen to count only unique ones. 

- 0.2
- 1.5 
- 2.5
- 7.7

In [64]:
dataUN = data.drop_duplicates(subset='ID', keep='first', inplace=False)
dataM2000 = dataUN[(dataUN['Sex'] == 'M') & (dataUN['Year'] == 2000)]
dataM2000['Sport'].value_counts(normalize=True) #1.5

Athletics            0.187940
Swimming             0.091976
Football             0.060535
Boxing               0.058423
Rowing               0.050446
Wrestling            0.045049
Cycling              0.044580
Sailing              0.041061
Baseball             0.037776
Judo                 0.036133
Canoeing             0.030033
Shooting             0.029798
Hockey               0.029094
Handball             0.027687
Basketball           0.026044
Weightlifting        0.023698
Volleyball           0.019709
Water Polo           0.019709
Fencing              0.017128
Equestrianism        0.014782
Gymnastics           0.014782
Tennis               0.014313
Badminton            0.012670
Taekwondo            0.012670
Triathlon            0.012201
Diving               0.011966
Archery              0.008212
Table Tennis         0.007977
Beach Volleyball     0.007039
Modern Pentathlon    0.003754
Trampolining         0.002816
Name: Sport, dtype: float64

__3. What are the mean and standard deviation of height for female basketball players participated in the 2000 Olympics? Round the answer to the first decimal.__

- 178.5 and 7.2
- 179.4 and 10
- 180.7 and 6.7
- 182.4 and 9.1

In [70]:
dataF2000 = data[data['Year'] == 2000]
dataF2000.groupby(['Sport', 'Sex'])['Height'].describe() #182.4 9.1 ?????

                            count        mean        std    min     25%  \
Sport                 Sex
Archery               F      99.0  167.919192   5.100374  153.0  165.00
                      M     105.0  179.847619   7.242743  163.0  175.00
Athletics             F    1014.0  169.626233   7.778101  146.0  165.00
                      M    1416.0  181.487288   8.125942  151.0  175.00
Badminton             F     119.0  168.630252   6.616448  150.0  164.00
                      M     106.0  179.858491   6.622384  160.0  175.00
Baseball              M     189.0  182.386243   7.032147  147.0  178.00
Basketball            F     142.0  182.387324   9.139462  162.0  175.00
                      M     144.0  199.493056   9.005046  178.0  193.00
Beach Volleyball      F      48.0  177.291667   5.295355  165.0  174.75
                      M      48.0  192.875000   5.381707  180.0  190.00
Boxing                M     303.0  174.158416   9.185793  150.0  168.00
Canoeing              F     103.0  171.165049   5.473818  157.0  168.00
                      M     345.0  182.362319   7.089074  160.0  178.00
Cycling               F     167.0  168.538922   6.174909  150.0  165.00
                      M     451.0  179.314856   6.025002  160.0  175.00
Diving                F     115.0  162.269565   6.058663  147.0  158.00
                      M     123.0  171.008130   5.434402  159.0  167.00
Equestrianism         F     100.0  169.260000   6.614371  153.0  165.00
                      M     195.0  176.789744   7.171816  157.0  172.00
Fencing               F     132.0  172.325758   6.286416  158.0  168.00
                      M     212.0  183.283019   5.987752  164.0  180.00
Football              F     124.0  168.532258   6.836577  150.0  165.00
                      M     256.0  179.179688   6.766624  158.0  175.00
Gymnastics            F     491.0  153.219959   6.502785  136.0  150.00
                      M     642.0  166.512461   4.715692  157.0  163.00
Handball              F     146.0  174.630137   6.051519  160.0  170.00
                      M     176.0  189.931818   7.264466  166.0  185.00
Hockey                F     159.0  167.459119   5.803471  152.0  164.00
                      M     188.0  178.547872   6.461970  163.0  174.75
...                           ...         ...        ...    ...     ...
Modern Pentathlon     F      24.0  169.875000   5.227956  158.0  167.00
                      M      24.0  181.708333   3.581100  172.0  180.00
Rhythmic Gymnastics   F      84.0  167.095238   4.753234  154.0  164.00
Rowing                F     194.0  178.345361   7.145367  157.0  175.00
                      M     367.0  189.561308   8.005526  154.0  185.00
Sailing               F      95.0  169.905263   6.343155  150.0  165.00
                      M     306.0  180.915033   7.644518  163.0  176.00
Shooting              F     223.0  165.094170   6.809182  150.0  160.00
                      M     374.0  177.754011   6.267361  162.0  174.00
Softball              F     120.0  169.416667   6.462020  150.0  165.00
Swimming              F     748.0  172.772727   6.637220  150.0  168.00
                      M     970.0  186.635052   7.506228  160.0  181.00
Synchronized Swimming F     117.0  168.854701   5.530893  153.0  165.00
Table Tennis          F     131.0  165.045802   6.280449  145.0  160.00
                      M     136.0  177.110294   6.874184  165.0  172.00
Taekwondo             F      48.0  169.437500   7.204922  154.0  165.00
                      M      53.0  180.339623   8.451089  164.0  174.00
Tennis                F     125.0  171.792000   6.458673  150.0  168.00
                      M     122.0  184.204918   6.192422  170.0  180.00
Trampolining          F      11.0  161.454545   4.412791  154.0  158.00
                      M      12.0  173.750000   5.894913  165.0  169.50
Triathlon             F      47.0  166.148936   5.675955  155.0  162.50
                      M      52.0  179.653846   5.970137  164.0  176.00
Volleyball            F     138.0  181.731884   7.456482  153.0  178.00
                      M     141.0  196.113475   7.021490  174.0  192.00
Water Polo            F      78.0  174.782051   5.973203  162.0  172.00
                      M     153.0  190.058824   6.607646  175.0  186.00
Weightlifting         F      85.0  160.717647   7.682094  145.0  155.00
                      M     155.0  170.090323  10.158080  147.0  163.00
Wrestling             M     313.0  174.549521   9.304583  155.0  167.00

                             50%     75%    max
Sport                 Sex
Archery               F    168.0  170.00  185.0
                      M    180.0  185.00  197.0
Athletics             F    170.0  174.00  193.0
                      M    182.0  187.00  205.0
Badminton             F    169.0  173.00  183.0
                      M    180.0  184.75  199.0
Baseball              M    183.0  186.00  206.0
Basketball            F    182.0  190.00  213.0
                      M    198.0  205.25  226.0
Beach Volleyball      F    178.0  180.25  188.0
                      M    193.0  196.00  208.0
Boxing                M    174.0  180.00  204.0
Canoeing              F    172.0  175.00  184.0
                      M    182.0  187.00  203.0
Cycling               F    168.0  172.00  201.0
                      M    180.0  183.00  198.0
Diving                F    163.0  165.50  178.0
                      M    170.0  174.00  186.0
Equestrianism         F    170.0  173.00  184.0
                      M    178.0  182.00  195.0
Fencing               F    172.5  176.00  187.0
                      M    183.0  187.00  196.0
Football              F    169.0  173.00  189.0
                      M    180.0  184.00  200.0
Gymnastics            F    153.0  157.00  167.0
                      M    166.0  170.00  180.0
Handball              F    174.5  179.00  190.0
                      M    190.0  195.00  211.0
Hockey                F    167.0  170.50  190.0
                      M    178.0  182.00  200.0
...                          ...     ...    ...
Modern Pentathlon     F    171.0  172.25  180.0
                      M    182.0  184.00  188.0
Rhythmic Gymnastics   F    167.0  170.25  176.0
Rowing                F    180.0  183.00  193.0
                      M    190.0  196.00  208.0
Sailing               F    170.0  174.50  183.0
                      M    181.0  185.00  213.0
Shooting              F    165.0  169.00  186.0
                      M    178.0  182.00  213.0
Softball              F    169.0  173.00  190.0
Swimming              F    173.0  177.00  193.0
                      M    186.0  192.00  209.0
Synchronized Swimming F    169.0  172.00  182.0
Table Tennis          F    165.0  170.00  181.0
                      M    177.0  181.25  192.0
Taekwondo             F    170.0  175.25  183.0
                      M    180.0  186.00  201.0
Tennis                F    172.0  176.00  191.0
                      M    184.5  190.00  198.0
Trampolining          F    163.0  164.50  167.0
                      M    174.0  176.25  185.0
Triathlon             F    167.0  169.50  180.0
                      M    180.0  183.25  193.0
Volleyball            F    182.0  186.00  204.0
                      M    197.0  201.00  217.0
Water Polo            F    175.0  179.75  190.0
                      M    190.0  195.00  206.0
Weightlifting         F    161.0  167.00  180.0
                      M    170.0  178.00  193.0
Wrestling             M    175.0  181.00  204.0

[62 rows x 8 columns]

__4. Find a sportsperson participated in the 2002 Olympics, with the highest weight among other participants of the same Olympics. What sport did he or she do?__

- Judo
- Bobsleigh 
- Weightlifting
- Boxing

In [44]:
data2002 = data[data['Year'] == 2002]
data2002[data2002['Weight'] == data2002['Weight'].max()]['Sport'] #Bobsleigh

99154    Bobsleigh
Name: Sport, dtype: object

__5. How many times did Pawe Abratkiewicz participate in the Olympics held in different years?__

- 0
- 1 
- 2
- 3

In [87]:
data[data['Name'] == 'Pawe Abratkiewicz'].drop_duplicates(subset='Year', keep='first', inplace=False)['ID'].count() #3

3

__6. How many silver medals in tennis did Australia win at the 2000 Olympics?__

- 0
- 1 
- 2 
- 3

In [90]:
data[(data['Sport'] == 'Tennis') & (data['Team'] == 'Australia') 
     & (data['Medal'] == 'Silver') & (data['Year'] == 2000)]['Medal'].count() #2

2

__7. Is it true that Switzerland won fewer medals than Serbia at the 2016 Olympics? Do not consider NaN values in _Medal_ column.__ 

- Yes 
- No

In [111]:
dataSaS = data[((data['Team'] == 'Switzerland') | (data['Team'] == 'Serbia')) & (data['Year'] == 2016)]
dataSaS2 = dataSaS.drop(['Age', 'Height', 'Weight'], axis=1 )
dataSaS2.dropna(inplace=True)
dataSaS2.groupby(['Team'])['Medal'].count() #No

Team
Serbia         54
Switzerland    11
Name: Medal, dtype: int64

__8. What age category did the fewest and the most participants of the 2014 Olympics belong to?__
- [45-55] and [25-35) correspondingly
- [45-55] and [15-25) correspondingly
- [35-45] and [25-35) correspondingly
- [45-55] and [35-45) correspondingly

In [131]:
data2014 = dataUN[dataUN['Year'] == 2014]
data2014[(data2014['Age'] >= 15) & (data2014['Age'] < 25)]['ID'].count(), \
data2014[(data2014['Age'] >= 25) & (data2014['Age'] < 35)]['ID'].count(), \
data2014[(data2014['Age'] >= 35) & (data2014['Age'] < 45)]['ID'].count(), \
data2014[(data2014['Age'] >= 45) & (data2014['Age'] <= 55)]['ID'].count() # [45-55] and [15-25)

(987, 546, 16, 2)

__9. Is it true that there were Summer Olympics held in Lake Placid? Is it true that there were Winter Olympics held in Sankt Moritz?__

- Yes, Yes
- Yes, No
- No, Yes 
- No, No

In [117]:
data[(data['Season'] == 'Summer') & (data['City'] == 'Lake Placid')]['City'].count(), \
data[(data['Season'] == 'Winter') & (data['City'] == 'Sankt Moritz')]['City'].count() #No, Yes

(0, 1657)

__10. What is the absolute difference between the number of unique sports at the 1995 Olympics and 2016 Olympics?__

- 16
- 24
- 26
- 34

In [124]:
data2014 = data[data['Year'] == 2016].drop_duplicates(subset='Sport', keep='first', inplace=False)['Sport'].count()
data1995 = data[data['Year'] == 1995].drop_duplicates(subset='Sport', keep='first', inplace=False)['Sport'].count()
data1995 - data2014 #34

-34